// DO NOT MODIFY THIS FILE
// This file is generated by the Firebase Studio.
// To modify, edit src/lib/firebase-client.ts and src/lib/firebase-server.ts instead.

import { initializeApp, getApps, getApp, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "velocitytype",
  "appId": "1:446119994650:web:90d6b55101d7d8902d78a3",
  "storageBucket": "velocitytype.firebasestorage.app",
  "apiKey": "AIzaSyDATHcpSp8ZpmgT8WK70YINfFTng40gt5I",
  "authDomain": "velocitytype.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "446119994650"
};

function initializeFirebase(config: any): { app: FirebaseApp, auth: Auth, db: Firestore } {
  const app = !getApps().length ? initializeApp(config) : getApp();
  const auth = getAuth(app);
  const db = getFirestore(app);
  return { app, auth, db };
}

function getClientInitializedFirebase() {
  return initializeFirebase(firebaseConfig);
}

function getServerInitializedFirebase() {
  return initializeFirebase(firebaseConfig);
}

export { firebaseConfig, getClientInitializedFirebase, getServerInitializedFirebase };
